Traceback (most recent call last):
  File "/home/cs-likm/dataset/GAs.py", line 965, in <module>
    global_data, global_labels, global_label_dict = _preprecess_data(run_which)
  File "/home/cs-likm/dataset/GAs.py", line 104, in _preprecess_data
    data = np.genfromtxt(loc_args['file-name'], delimiter=loc_args['delimiter'])[:, :-1]
  File "/opt/software/python-3.6.3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 1700, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/opt/software/python-3.6.3/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 262, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/opt/software/python-3.6.3/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 618, in open
    raise IOError("%s not found." % path)
OSError: Breast.csv not found.
Connection closed by 11.11.1.100
